FROM debian:jessie
MAINTAINER dbrawand@nhs.net

#Initial packages install
#RUN apt-get update && apt-get -y upgrade
# add some convenience utils
#RUN apt-get -y install curl less make wget vim apt-utils

ADD . /zippy
RUN cd zippy && make install
# prepare genome
RUN cd zippy && make genome-download
RUN cd zippy && make genome-index

# get annotation
RUN cd zippy && make variation-download
RUN cd zippy && make refgene-download

# install zippy
RUN cd /zippy && make webservice

EXPOSE 80

CMD /bin/bash /zippy/zippyd.sh
#The path of zippy.py is
# sudo docker run -it lucioric/zippy usr/local/zippy/venv/bin/python /zippy/zippy/zippy.py