FROM debian:jessie
MAINTAINER dbrawand@nhs.net

ADD . /zippy

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sudo
RUN sudo apt-get install -y less make wget curl vim apt-utils

RUN cd /zippy && make print_flags env_suffix=_docker distro=ubuntu
RUN cd /zippy && make very_essential env_suffix=_docker distro=ubuntu
RUN cd /zippy && make cleansoftware env_suffix=_docker distro=ubuntu
RUN cd /zippy && make cleandb env_suffix=_docker distro=ubuntu

RUN cd /zippy && make install env_suffix=_docker distro=ubuntu
RUN cd /zippy && make webservice env_suffix=_docker distro=ubuntu
# prepare genome
RUN cd /zippy && make genome-download env_suffix=_docker distro=ubuntu
RUN cd /zippy && make genome-index env_suffix=_docker distro=ubuntu

# get annotation
RUN cd /zippy && make variation-download env_suffix=_docker distro=ubuntu
RUN cd /zippy && make refgene-download env_suffix=_docker distro=ubuntu

EXPOSE 80

CMD /bin/bash /zippy/zippyd.sh
#The command for executing zippy.py is
# sudo docker run -it lucioric/zippy usr/local/zippy/venv/bin/python /zippy/zippy/zippy.py